[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
primaryColor = "#6366f1"
backgroundColor = "#fafbfc"
secondaryBackgroundColor = "#ffffff"
textColor = "#1a202c"
font = "sans serif"

[browser]
gatherUsageStats = false
